export type AchievementConditionField =
  | 'totalClicks'
  | 'totalMonstersDefeated'
  | 'level'
  | 'totalTikTikEarned'
  | 'unlockedMonstersCount'
  | 'clickPower'
  | 'maxMultiTouch';

export interface Achievement {
  id: number;
  nameKey: string;
  descKey: string;
  conditionField: AchievementConditionField;
  conditionValue: number;
  rewardTikTik: number;
  rewardXp: number;
}

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 1,
    nameKey: 'ach_first_tap',
    descKey: 'ach_first_tap_desc',
    conditionField: 'totalClicks',
    conditionValue: 1,
    rewardTikTik: 50,
    rewardXp: 5,
  },
  {
    id: 2,
    nameKey: 'ach_100_clicks',
    descKey: 'ach_100_clicks_desc',
    conditionField: 'totalClicks',
    conditionValue: 100,
    rewardTikTik: 200,
    rewardXp: 20,
  },
  {
    id: 3,
    nameKey: 'ach_1000_clicks',
    descKey: 'ach_1000_clicks_desc',
    conditionField: 'totalClicks',
    conditionValue: 1000,
    rewardTikTik: 1000,
    rewardXp: 100,
  },
  {
    id: 4,
    nameKey: 'ach_10000_clicks',
    descKey: 'ach_10000_clicks_desc',
    conditionField: 'totalClicks',
    conditionValue: 10000,
    rewardTikTik: 5000,
    rewardXp: 400,
  },
  {
    id: 5,
    nameKey: 'ach_first_monster',
    descKey: 'ach_first_monster_desc',
    conditionField: 'totalMonstersDefeated',
    conditionValue: 1,
    rewardTikTik: 500,
    rewardXp: 50,
  },
  {
    id: 6,
    nameKey: 'ach_10_monsters',
    descKey: 'ach_10_monsters_desc',
    conditionField: 'totalMonstersDefeated',
    conditionValue: 10,
    rewardTikTik: 100000,
    rewardXp: 1000,
  },
  {
    id: 7,
    nameKey: 'ach_level_2',
    descKey: 'ach_level_2_desc',
    conditionField: 'level',
    conditionValue: 2,
    rewardTikTik: 300,
    rewardXp: 0,
  },
  {
    id: 8,
    nameKey: 'ach_level_5',
    descKey: 'ach_level_5_desc',
    conditionField: 'level',
    conditionValue: 5,
    rewardTikTik: 5000,
    rewardXp: 0,
  },
  {
    id: 9,
    nameKey: 'ach_1000_tiktik',
    descKey: 'ach_1000_tiktik_desc',
    conditionField: 'totalTikTikEarned',
    conditionValue: 1000,
    rewardTikTik: 500,
    rewardXp: 25,
  },
  {
    id: 10,
    nameKey: 'ach_10000_tiktik',
    descKey: 'ach_10000_tiktik_desc',
    conditionField: 'totalTikTikEarned',
    conditionValue: 10000,
    rewardTikTik: 3000,
    rewardXp: 100,
  },
  {
    id: 11,
    nameKey: 'ach_max_click',
    descKey: 'ach_max_click_desc',
    conditionField: 'clickPower',
    conditionValue: 10,
    rewardTikTik: 20000,
    rewardXp: 500,
  },
  {
    id: 12,
    nameKey: 'ach_multitouch',
    descKey: 'ach_multitouch_desc',
    conditionField: 'maxMultiTouch',
    conditionValue: 3,
    rewardTikTik: 2000,
    rewardXp: 80,
  },
  {
    id: 13,
    nameKey: 'ach_unlock_5_monsters',
    descKey: 'ach_unlock_5_monsters_desc',
    conditionField: 'unlockedMonstersCount',
    conditionValue: 5,
    rewardTikTik: 8000,
    rewardXp: 200,
  },
  {
    id: 14,
    nameKey: 'ach_all_monsters',
    descKey: 'ach_all_monsters_desc',
    conditionField: 'unlockedMonstersCount',
    conditionValue: 10,
    rewardTikTik: 50000,
    rewardXp: 1000,
  },

  // ── Tıklama ─────────────────────────────────────────────────────────────────
  {
    id: 15,
    nameKey: 'ach_500_clicks',
    descKey: 'ach_500_clicks_desc',
    conditionField: 'totalClicks',
    conditionValue: 500,
    rewardTikTik: 100,
    rewardXp: 10,
  },
  {
    id: 16,
    nameKey: 'ach_5000_clicks',
    descKey: 'ach_5000_clicks_desc',
    conditionField: 'totalClicks',
    conditionValue: 5000,
    rewardTikTik: 2500,
    rewardXp: 250,
  },
  {
    id: 17,
    nameKey: 'ach_50000_clicks',
    descKey: 'ach_50000_clicks_desc',
    conditionField: 'totalClicks',
    conditionValue: 50000,
    rewardTikTik: 20000,
    rewardXp: 2000,
  },
  {
    id: 18,
    nameKey: 'ach_100000_clicks',
    descKey: 'ach_100000_clicks_desc',
    conditionField: 'totalClicks',
    conditionValue: 100000,
    rewardTikTik: 50000,
    rewardXp: 5000,
  },
  {
    id: 19,
    nameKey: 'ach_500000_clicks',
    descKey: 'ach_500000_clicks_desc',
    conditionField: 'totalClicks',
    conditionValue: 500000,
    rewardTikTik: 200000,
    rewardXp: 15000,
  },
  {
    id: 20,
    nameKey: 'ach_1m_clicks',
    descKey: 'ach_1m_clicks_desc',
    conditionField: 'totalClicks',
    conditionValue: 1000000,
    rewardTikTik: 1000000,
    rewardXp: 30000,
  },

  // ── Canavar Yenme ────────────────────────────────────────────────────────────
  {
    id: 21,
    nameKey: 'ach_5_monsters',
    descKey: 'ach_5_monsters_desc',
    conditionField: 'totalMonstersDefeated',
    conditionValue: 5,
    rewardTikTik: 2000,
    rewardXp: 200,
  },
  {
    id: 22,
    nameKey: 'ach_25_monsters',
    descKey: 'ach_25_monsters_desc',
    conditionField: 'totalMonstersDefeated',
    conditionValue: 25,
    rewardTikTik: 15000,
    rewardXp: 500,
  },
  {
    id: 23,
    nameKey: 'ach_50_monsters',
    descKey: 'ach_50_monsters_desc',
    conditionField: 'totalMonstersDefeated',
    conditionValue: 50,
    rewardTikTik: 40000,
    rewardXp: 1500,
  },
  {
    id: 24,
    nameKey: 'ach_100_monsters',
    descKey: 'ach_100_monsters_desc',
    conditionField: 'totalMonstersDefeated',
    conditionValue: 100,
    rewardTikTik: 100000,
    rewardXp: 3000,
  },
  {
    id: 25,
    nameKey: 'ach_500_monsters',
    descKey: 'ach_500_monsters_desc',
    conditionField: 'totalMonstersDefeated',
    conditionValue: 500,
    rewardTikTik: 500000,
    rewardXp: 10000,
  },
  {
    id: 26,
    nameKey: 'ach_1000_monsters',
    descKey: 'ach_1000_monsters_desc',
    conditionField: 'totalMonstersDefeated',
    conditionValue: 1000,
    rewardTikTik: 2000000,
    rewardXp: 30000,
  },
  {
    id: 27,
    nameKey: 'ach_10000_monsters',
    descKey: 'ach_10000_monsters_desc',
    conditionField: 'totalMonstersDefeated',
    conditionValue: 10000,
    rewardTikTik: 10000000,
    rewardXp: 100000,
  },

  // ── Seviye ──────────────────────────────────────────────────────────────────
  {
    id: 28,
    nameKey: 'ach_level_10',
    descKey: 'ach_level_10_desc',
    conditionField: 'level',
    conditionValue: 10,
    rewardTikTik: 10000,
    rewardXp: 0,
  },
  {
    id: 29,
    nameKey: 'ach_level_15',
    descKey: 'ach_level_15_desc',
    conditionField: 'level',
    conditionValue: 15,
    rewardTikTik: 20000,
    rewardXp: 0,
  },
  {
    id: 30,
    nameKey: 'ach_level_20',
    descKey: 'ach_level_20_desc',
    conditionField: 'level',
    conditionValue: 20,
    rewardTikTik: 35000,
    rewardXp: 0,
  },
  {
    id: 31,
    nameKey: 'ach_level_30',
    descKey: 'ach_level_30_desc',
    conditionField: 'level',
    conditionValue: 30,
    rewardTikTik: 80000,
    rewardXp: 0,
  },
  {
    id: 32,
    nameKey: 'ach_level_50',
    descKey: 'ach_level_50_desc',
    conditionField: 'level',
    conditionValue: 50,
    rewardTikTik: 200000,
    rewardXp: 0,
  },
  {
    id: 33,
    nameKey: 'ach_level_100',
    descKey: 'ach_level_100_desc',
    conditionField: 'level',
    conditionValue: 100,
    rewardTikTik: 1000000,
    rewardXp: 0,
  },

  // ── Kazanılan TıkTık ────────────────────────────────────────────────────────
  {
    id: 34,
    nameKey: 'ach_100_tiktik',
    descKey: 'ach_100_tiktik_desc',
    conditionField: 'totalTikTikEarned',
    conditionValue: 100,
    rewardTikTik: 50,
    rewardXp: 5,
  },
  {
    id: 35,
    nameKey: 'ach_100k_tiktik',
    descKey: 'ach_100k_tiktik_desc',
    conditionField: 'totalTikTikEarned',
    conditionValue: 100000,
    rewardTikTik: 10000,
    rewardXp: 500,
  },
  {
    id: 36,
    nameKey: 'ach_1m_tiktik',
    descKey: 'ach_1m_tiktik_desc',
    conditionField: 'totalTikTikEarned',
    conditionValue: 1000000,
    rewardTikTik: 80000,
    rewardXp: 2000,
  },
  {
    id: 37,
    nameKey: 'ach_10m_tiktik',
    descKey: 'ach_10m_tiktik_desc',
    conditionField: 'totalTikTikEarned',
    conditionValue: 10000000,
    rewardTikTik: 500000,
    rewardXp: 10000,
  },
  {
    id: 38,
    nameKey: 'ach_100m_tiktik',
    descKey: 'ach_100m_tiktik_desc',
    conditionField: 'totalTikTikEarned',
    conditionValue: 100000000,
    rewardTikTik: 3000000,
    rewardXp: 50000,
  },

  // ── Çoklu Dokunuş ───────────────────────────────────────────────────────────
  {
    id: 39,
    nameKey: 'ach_multitouch_2',
    descKey: 'ach_multitouch_2_desc',
    conditionField: 'maxMultiTouch',
    conditionValue: 2,
    rewardTikTik: 500,
    rewardXp: 30,
  },
  {
    id: 40,
    nameKey: 'ach_multitouch_4',
    descKey: 'ach_multitouch_4_desc',
    conditionField: 'maxMultiTouch',
    conditionValue: 4,
    rewardTikTik: 8000,
    rewardXp: 200,
  },
  {
    id: 41,
    nameKey: 'ach_multitouch_max',
    descKey: 'ach_multitouch_max_desc',
    conditionField: 'maxMultiTouch',
    conditionValue: 6,
    rewardTikTik: 50000,
    rewardXp: 1000,
  },

  // ── Tıklama Gücü ────────────────────────────────────────────────────────────
  {
    id: 42,
    nameKey: 'ach_click_3',
    descKey: 'ach_click_3_desc',
    conditionField: 'clickPower',
    conditionValue: 3,
    rewardTikTik: 1000,
    rewardXp: 50,
  },
  {
    id: 43,
    nameKey: 'ach_click_5',
    descKey: 'ach_click_5_desc',
    conditionField: 'clickPower',
    conditionValue: 5,
    rewardTikTik: 5000,
    rewardXp: 150,
  },
  {
    id: 44,
    nameKey: 'ach_click_7',
    descKey: 'ach_click_7_desc',
    conditionField: 'clickPower',
    conditionValue: 7,
    rewardTikTik: 12000,
    rewardXp: 350,
  },

  // ── Canavar Açma ─────────────────────────────────────────────────────────────
  {
    id: 45,
    nameKey: 'ach_unlock_3',
    descKey: 'ach_unlock_3_desc',
    conditionField: 'unlockedMonstersCount',
    conditionValue: 3,
    rewardTikTik: 2000,
    rewardXp: 100,
  },
  {
    id: 46,
    nameKey: 'ach_unlock_8',
    descKey: 'ach_unlock_8_desc',
    conditionField: 'unlockedMonstersCount',
    conditionValue: 8,
    rewardTikTik: 20000,
    rewardXp: 500,
  },
  {
    id: 47,
    nameKey: 'ach_unlock_12',
    descKey: 'ach_unlock_12_desc',
    conditionField: 'unlockedMonstersCount',
    conditionValue: 12,
    rewardTikTik: 60000,
    rewardXp: 1500,
  },
  {
    id: 48,
    nameKey: 'ach_unlock_15',
    descKey: 'ach_unlock_15_desc',
    conditionField: 'unlockedMonstersCount',
    conditionValue: 15,
    rewardTikTik: 150000,
    rewardXp: 3000,
  },
  {
    id: 49,
    nameKey: 'ach_unlock_18',
    descKey: 'ach_unlock_18_desc',
    conditionField: 'unlockedMonstersCount',
    conditionValue: 18,
    rewardTikTik: 400000,
    rewardXp: 7000,
  },
  {
    id: 50,
    nameKey: 'ach_unlock_all',
    descKey: 'ach_unlock_all_desc',
    conditionField: 'unlockedMonstersCount',
    conditionValue: 20,
    rewardTikTik: 2000000,
    rewardXp: 20000,
  },
];
